/* Nebula fragment shader — samples a packed R/G/B noise texture and applies
 * the full SHO colour palette (dark) or pantone scale (light) at runtime.
 *
 * Texture layout (generated by scripts/generate-nebula.mjs):
 *   R = S II  / layer 0 — raw fBm noise value [0, 1]
 *   G = H-α   / layer 1 — raw fBm noise value [0, 1]
 *   B = O III / layer 2 — raw fBm noise value [0, 1]
 *   A = 1.0   (always opaque; per-pixel alpha is computed from noise here)
 */
const src = /* glsl */`
precision mediump float;

uniform sampler2D u_nebula;      // packed noise: R=S II, G=H-α, B=O III
uniform float     u_opacity;     // global opacity scale
uniform float     u_light;       // 0.0 = dark (SHO), 1.0 = light (pantone)
uniform float     u_w0;          // S II / layer-0 prominence weight
uniform float     u_w1;          // H-α / layer-1 prominence weight
uniform float     u_w2;          // O III / layer-2 prominence weight
uniform sampler2D u_star_light;  // star-glow accumulation FBO (screen space)
uniform float     u_illum_boost; // how strongly star clusters brighten the nebula
varying vec2      v_uv;
varying vec2      v_screen_uv;

// Noise values below THRESHOLD contribute zero alpha (cuts dead space around clouds).
const float THRESHOLD = 0.01;

float nebulaAlpha(float v) {
  float n = max(0.0, (v - THRESHOLD) / (1.0 - THRESHOLD));
  // Squared curve: bright dense cores but still preserves enough cloud body.
  // n³ was too aggressive — crushed the mid-density cloud mass to near-zero.
  return n * n;
}

// ── Dark palette — Hubble SHO ─────────────────────────────────────────────────
// Gradient stops span fBm range 0.38–1.00; values below 0.38 clamp to first stop.

vec3 darkS2(float v) {
  // 0.38→[50,5,0]  0.52→[130,30,5]  0.65→[210,80,10]  0.80→[240,145,40]  1.00→[255,200,90]
  vec3 c0 = vec3(0.196, 0.020, 0.000);
  vec3 c1 = vec3(0.510, 0.118, 0.020);
  vec3 c2 = vec3(0.824, 0.314, 0.039);
  vec3 c3 = vec3(0.941, 0.569, 0.157);
  vec3 c4 = vec3(1.000, 0.784, 0.353);
  if      (v < 0.52) return mix(c0, c1, clamp((v - 0.38) / 0.14, 0.0, 1.0));
  else if (v < 0.65) return mix(c1, c2, (v - 0.52) / 0.13);
  else if (v < 0.80) return mix(c2, c3, (v - 0.65) / 0.15);
  else               return mix(c3, c4, clamp((v - 0.80) / 0.20, 0.0, 1.0));
}

vec3 darkHa(float v) {
  // 0.38→[0,35,10]  0.52→[10,90,30]  0.65→[25,150,55]  0.80→[70,200,90]  1.00→[140,230,140]
  vec3 c0 = vec3(0.000, 0.137, 0.039);
  vec3 c1 = vec3(0.039, 0.353, 0.118);
  vec3 c2 = vec3(0.098, 0.588, 0.216);
  vec3 c3 = vec3(0.275, 0.784, 0.353);
  vec3 c4 = vec3(0.549, 0.902, 0.549);
  if      (v < 0.52) return mix(c0, c1, clamp((v - 0.38) / 0.14, 0.0, 1.0));
  else if (v < 0.65) return mix(c1, c2, (v - 0.52) / 0.13);
  else if (v < 0.80) return mix(c2, c3, (v - 0.65) / 0.15);
  else               return mix(c3, c4, clamp((v - 0.80) / 0.20, 0.0, 1.0));
}

vec3 darkO3(float v) {
  // 0.38→[0,15,55]  0.52→[10,55,130]  0.65→[20,115,200]  0.80→[40,170,230]  1.00→[100,215,255]
  vec3 c0 = vec3(0.000, 0.059, 0.216);
  vec3 c1 = vec3(0.039, 0.216, 0.510);
  vec3 c2 = vec3(0.078, 0.451, 0.784);
  vec3 c3 = vec3(0.157, 0.667, 0.902);
  vec3 c4 = vec3(0.392, 0.843, 1.000);
  if      (v < 0.52) return mix(c0, c1, clamp((v - 0.38) / 0.14, 0.0, 1.0));
  else if (v < 0.65) return mix(c1, c2, (v - 0.52) / 0.13);
  else if (v < 0.80) return mix(c2, c3, (v - 0.65) / 0.15);
  else               return mix(c3, c4, clamp((v - 0.80) / 0.20, 0.0, 1.0));
}

// ── Light palette — pantone scale ─────────────────────────────────────────────

vec3 lightL0(float v) {
  // 0.38→[172,160,147]  0.65→[209,202,195]  1.00→[246,244,243]
  vec3 c0 = vec3(0.675, 0.627, 0.576);
  vec3 c1 = vec3(0.820, 0.792, 0.765);
  vec3 c2 = vec3(0.965, 0.957, 0.953);
  if (v < 0.65) return mix(c0, c1, clamp((v - 0.38) / 0.27, 0.0, 1.0));
  else          return mix(c1, c2, clamp((v - 0.65) / 0.35, 0.0, 1.0));
}

vec3 lightL1(float v) {
  // 0.38→[108,96,83]  0.65→[154,139,123]  1.00→[227,223,219]
  vec3 c0 = vec3(0.424, 0.376, 0.325);
  vec3 c1 = vec3(0.604, 0.545, 0.482);
  vec3 c2 = vec3(0.890, 0.875, 0.859);
  if (v < 0.65) return mix(c0, c1, clamp((v - 0.38) / 0.27, 0.0, 1.0));
  else          return mix(c1, c2, clamp((v - 0.65) / 0.35, 0.0, 1.0));
}

vec3 lightL2(float v) {
  // 0.38→[154,139,123]  0.65→[190,181,171]  1.00→[227,223,219]
  vec3 c0 = vec3(0.604, 0.545, 0.482);
  vec3 c1 = vec3(0.745, 0.710, 0.671);
  vec3 c2 = vec3(0.890, 0.875, 0.859);
  if (v < 0.65) return mix(c0, c1, clamp((v - 0.38) / 0.27, 0.0, 1.0));
  else          return mix(c1, c2, clamp((v - 0.65) / 0.35, 0.0, 1.0));
}

void main() {
  vec4 pkt = texture2D(u_nebula, v_uv);
  float v0 = pkt.r;  // S II / layer 0
  float v1 = pkt.g;  // H-α  / layer 1
  float v2 = pkt.b;  // O III / layer 2

  // Per-layer alpha (post-threshold, 0-1) × prominence weight
  float a0 = nebulaAlpha(v0) * u_w0;
  float a1 = nebulaAlpha(v1) * u_w1;
  float a2 = nebulaAlpha(v2) * u_w2;

  // Colour from the appropriate palette
  vec3 col0 = u_light > 0.5 ? lightL0(v0) : darkS2(v0);
  vec3 col1 = u_light > 0.5 ? lightL1(v1) : darkHa(v1);
  vec3 col2 = u_light > 0.5 ? lightL2(v2) : darkO3(v2);

  // Cross-layer scattering: Hα bleeds a little colour into adjacent emission bands.
  // Real nebulae have overlapping ionisation zones rather than pure independent layers.
  col0 += 0.08 * col1 * a1;   // Hα → SII
  col2 += 0.05 * col1 * a1;   // Hα → OIII

  // Additive blend
  vec3 rgb = clamp(col0 * a0 + col1 * a1 + col2 * a2, 0.0, 1.0);

  // ── Star → nebula illumination ─────────────────────────────────────────────
  // Sample the screen-space star-illumination FBO — each star contributes a wide
  // soft gaussian halo drawn additively, so overlapping halos from clusters
  // compound naturally into bright spots before reaching the nebula shader.
  vec3  starLight  = texture2D(u_star_light, v_screen_uv).rgb * u_illum_boost;
  float illumLuma  = dot(starLight, vec3(0.299, 0.587, 0.114));

  // Boost nebula colour and allow a subtle spectral tint from star chromaticity.
  rgb = clamp(rgb * (1.0 + illumLuma) + starLight * 0.18, 0.0, 1.0);

  // Density boost: where stars cluster, nebula edges scatter a little more light.
  float rawA = max(max(a0, a1), a2);
  float litA = clamp(rawA * (1.0 + illumLuma * 0.7) + illumLuma * 0.06, 0.0, 1.0);
  float a    = litA * u_opacity;

  // Premultiplied output
  gl_FragColor = vec4(rgb * a, a);
}
`;

export default src;
