// ─── Debug & renderer selection ────────────────────────────────────────────────

/** Show a frametime / FPS overlay in the top-right corner of the canvas. */
export const DEBUG_FRAMETIME = false;

/**
 * 'auto'   — use WebGL when available, fall back to Canvas 2D
 * 'webgl'  — always use WebGL (no fallback)
 * 'canvas' — always use Canvas 2D
 */
export const RENDERER: 'auto' | 'webgl' | 'canvas' = 'auto';

// ─── Stars ────────────────────────────────────────────────────────────────────

export const STAR_COUNT             = 360;
export const STAR_RADIUS_MIN        = 0.3;
export const STAR_RADIUS_MAX        = 2.0;
export const STAR_TWINKLE_SPEED_MIN = 0.003;
export const STAR_TWINKLE_SPEED_MAX = 0.011;
export const STAR_TWINKLE_AMPLITUDE = 0.2;

// ─── Shooting stars ───────────────────────────────────────────────────────────

export const SHOOT_MAX_COUNT            = 4;
export const SHOOT_SPAWN_INTERVAL       = 80;   // frames between spawn attempts
export const SHOOT_SPAWN_CHANCE         = 0.3;  // probability per attempt
export const SHOOT_ANGLE_MIN            = 20;   // degrees
export const SHOOT_ANGLE_MAX            = 40;   // degrees
export const SHOOT_SPEED_MIN            = 9;
export const SHOOT_SPEED_MAX            = 16;
export const SHOOT_TRAIL_MIN            = 160;
export const SHOOT_TRAIL_MAX            = 360;
export const SHOOT_FADE_IN              = 0.04;
export const SHOOT_HOLD_DIST_FRAC_MIN   = 0.5;  // fraction of min(w,h) before fade-out (min)
export const SHOOT_HOLD_DIST_FRAC_MAX   = 1;    // fraction of min(w,h) before fade-out (max)
export const SHOOT_FADE_OUT             = 0.015;
export const SHOOT_GLOW_RADIUS          = 3.5;
export const SHOOT_LINE_WIDTH           = 1.5;

// ─── Explosions ───────────────────────────────────────────────────────────────

export const EXPLOSION_PARTICLE_COUNT   = 32;
export const EXPLOSION_SPEED_MIN        = 0.4;
export const EXPLOSION_SPEED_MAX        = 5.5;
export const EXPLOSION_ALPHA_MIN        = 0.55;
export const EXPLOSION_ALPHA_MAX        = 1.0;
export const EXPLOSION_DECAY_MIN        = 0.011;
export const EXPLOSION_DECAY_MAX        = 0.026;
export const EXPLOSION_RADIUS_MIN       = 0.4;
export const EXPLOSION_RADIUS_MAX       = 2.4;
export const EXPLOSION_RING_INIT_ALPHA  = 0.75;
export const EXPLOSION_RING_EXPAND      = 3.5;
export const EXPLOSION_RING_FADE        = 0.032;
export const EXPLOSION_PARTICLE_DRAG    = 0.97;
export const EXPLOSION_PARTICLE_GRAVITY = 0.03;

// ─── Nebula (WebGL only) ──────────────────────────────────────────────────────

/** Master toggle — set to false to skip all nebula work. */
export const NEBULA_ENABLED     = true;

/** Overall nebula layer opacity (0–1). */
export const NEBULA_OPACITY     = 0.95;

/**
 * Per-layer prominence weights applied in the nebula shader.
 *
 * H-α (hydrogen) is most abundant — it always gets the top weight.
 * S II and O III alternate randomly each page load: one gets the HIGH weight,
 * the other the LOW weight (decided by NEBULA_SO_FLIP in the renderer).
 *
 * Range 0–1. Multiply each layer's texel alpha before blending.
 */
export const NEBULA_WEIGHT_HYDROGEN = 1.00;  // H-α  — most prominent
export const NEBULA_WEIGHT_SO_HI    = 0.85;  // whichever of S II / O III wins the coin flip
export const NEBULA_WEIGHT_SO_LO    = 0.65;  // the other one

/**
 * Number of variants pre-generated by scripts/generate-nebula.mjs.
 * A random one is chosen on every page load.
 */
export const NEBULA_BAKED_COUNT = 6;

// ─── Bake-time constants (scripts/generate-nebula.mjs) ───────────────────────
// These are NOT used at runtime; they exist here as the single source of truth
// for re-running the generator. After editing any value below, re-run:
//   npm run generate:nebula

/** fBm octave count — more octaves = richer detail, slower generation. */
export const NEBULA_OCTAVES     = 5;

/** Base frequency of the noise (lower = larger cloud formations). */
export const NEBULA_SCALE       = 2.5;

/** Amplitude decay per octave (0–1). Lower = smoother/softer. */
export const NEBULA_PERSISTENCE = 0.5;

/** Frequency multiplier per octave. */
export const NEBULA_LACUNARITY  = 2.0;

/** Base seed for the permutation table; each variant offsets this by its index. */
export const NEBULA_SEED        = 42;

/**
 * Box-blur passes applied after noise sampling.
 * Each pass softens edges; 2–3 is usually enough.
 */
export const NEBULA_BLUR_PASSES = 2;

/**
 * Noise values below this threshold are fully transparent (cuts dead space).
 * Range 0–1. Higher = sparser, more concentrated clouds.
 */
export const NEBULA_THRESHOLD   = 0.38;

/**
 * Number of independently-colored noise layers composited per nebula.
 * Each layer uses a distinct seed offset so cloud shapes are independent.
 */
export const NEBULA_LAYER_COUNT = 3;

/**
 * Per-layer color gradient stops for dark mode — Hubble SHO palette.
 * Layer 0 = S II  (Sulfur II)   → reds / golds
 * Layer 1 = H-α   (Hydrogen-α) → greens
 * Layer 2 = O III (Oxygen III)  → blues / teals
 *
 * Format: [noiseValue 0–1, [R, G, B] 0–255], sorted ascending by noise value.
 */
export const NEBULA_DARK_LAYERS: [number, [number, number, number]][][] = [
  // ── S II — sulfur (red / gold channel) ──────────────────────────────────
  [
    [0.38, [50,   5,   0]],   // near-black crimson
    [0.52, [130,  30,   5]],  // dark burgundy
    [0.65, [210,  80,  10]],  // burnt orange
    [0.80, [240, 145,  40]],  // amber
    [1.00, [255, 200,  90]],  // bright gold
  ],
  // ── H-α — hydrogen (green channel) ────────────────────────────────────
  [
    [0.38, [  0,  35,  10]],  // near-black green
    [0.52, [ 10,  90,  30]],  // forest green
    [0.65, [ 25, 150,  55]],  // mid green
    [0.80, [ 70, 200,  90]],  // bright green
    [1.00, [140, 230, 140]],  // pale yellow-green
  ],
  // ── O III — oxygen (blue / teal channel) ───────────────────────────────
  [
    [0.38, [  0,  15,  55]],  // deep navy
    [0.52, [ 10,  55, 130]],  // cobalt
    [0.65, [ 20, 115, 200]],  // sky blue
    [0.80, [ 40, 170, 230]],  // teal
    [1.00, [100, 215, 255]],  // electric cyan
  ],
];

/**
 * Per-layer color gradient stops for light mode — grayscale palette.
 * Three subtly-tinted gray layers for gentle depth without harsh color.
 * Layer 0 = warm gray  | Layer 1 = neutral gray  | Layer 2 = cool gray
 */
export const NEBULA_LIGHT_LAYERS: [number, [number, number, number]][][] = [
  // ── warm gray ────────────────────────────────────────────────────────────
  [
    [0.38, [200, 195, 190]],
    [0.65, [220, 215, 210]],
    [1.00, [240, 238, 235]],
  ],
  // ── neutral gray ─────────────────────────────────────────────────────────
  [
    [0.38, [190, 190, 190]],
    [0.65, [210, 210, 210]],
    [1.00, [235, 235, 235]],
  ],
  // ── cool gray ────────────────────────────────────────────────────────────
  [
    [0.38, [188, 192, 200]],
    [0.65, [208, 212, 222]],
    [1.00, [230, 234, 245]],
  ],
];
