import { useEffect, useState } from 'react';

import { NEBULA_BAKED_COUNT, NEBULA_LAYER_COUNT } from './config';

interface NebulaState {
  dark:  ImageBitmap[] | null;
  light: ImageBitmap[] | null;
}

// Keyed on `window` so the cache survives client-side navigations (window is
// never torn down) but resets on a real browser refresh (window is recreated).
// This also works correctly in Next.js dev mode where module scope is
// re-evaluated on each navigation.
declare global {
  interface Window {
    __nebulaVariant?: number;
    __nebulaBitmaps?: NebulaState;
  }
}

function getCachedBitmaps(): NebulaState | null {
  return (typeof window !== 'undefined' && window.__nebulaBitmaps) || null;
}

/**
 * Loads a randomly-selected pre-baked nebula variant from /nebula/.
 * Fetches NEBULA_LAYER_COUNT layers for each theme in parallel (6 requests total).
 * Assets are generated by scripts/generate-nebula.mjs.
 * The chosen variant is cached on `window` for the lifetime of the browser
 * session so client-side navigations always show the same nebula.
 * When `enabled` is false (Canvas 2D renderer path), the hook is a no-op.
 */
export function useNebulaTexture(enabled: boolean): NebulaState {
  const [bitmaps, setBitmaps] = useState<NebulaState>(getCachedBitmaps() ?? { dark: null, light: null });

  useEffect(() => {
    if (!enabled || typeof window === 'undefined') return;

    // Already loaded this session — reuse and bail.
    if (window.__nebulaBitmaps) {
      setBitmaps(window.__nebulaBitmaps);
      return;
    }

    let cancelled = false;
    if (window.__nebulaVariant === undefined) {
      window.__nebulaVariant = Math.floor(Math.random() * NEBULA_BAKED_COUNT);
    }
    const v = window.__nebulaVariant;

    const loadLayer = (theme: string, layer: number) =>
      fetch(`/nebula/${theme}-${v}-${layer}.png`)
        .then(r => r.blob())
        .then(b => createImageBitmap(b));

    const darkRequests  = Array.from({ length: NEBULA_LAYER_COUNT }, (_, l) => loadLayer('dark',  l));
    const lightRequests = Array.from({ length: NEBULA_LAYER_COUNT }, (_, l) => loadLayer('light', l));

    Promise.all([...darkRequests, ...lightRequests])
      .then(all => {
        if (cancelled) return;
        window.__nebulaBitmaps = {
          dark:  all.slice(0, NEBULA_LAYER_COUNT),
          light: all.slice(NEBULA_LAYER_COUNT),
        };
        setBitmaps(window.__nebulaBitmaps);
      })
      .catch(err => {
        console.error('[useNebulaTexture] Failed to load nebula assets:', err);
      });

    return () => { cancelled = true; };
  }, [enabled]);

  return bitmaps;
}

