import { useEffect, useState } from 'react';

import { NEBULA_BAKED_COUNT, NEBULA_LAYER_COUNT } from './config';

interface NebulaState {
  dark:  ImageBitmap[] | null;
  light: ImageBitmap[] | null;
}

/**
 * Loads a randomly-selected pre-baked nebula variant from /nebula/.
 * Fetches NEBULA_LAYER_COUNT layers for each theme in parallel (6 requests total).
 * Assets are generated by scripts/generate-nebula.mjs.
 * When `enabled` is false (Canvas 2D renderer path), the hook is a no-op.
 */
export function useNebulaTexture(enabled: boolean): NebulaState {
  const [bitmaps, setBitmaps] = useState<NebulaState>({ dark: null, light: null });

  useEffect(() => {
    if (!enabled || typeof window === 'undefined') return;

    let cancelled = false;
    const v = Math.floor(Math.random() * NEBULA_BAKED_COUNT);

    const loadLayer = (theme: string, layer: number) =>
      fetch(`/nebula/${theme}-${v}-${layer}.png`)
        .then(r => r.blob())
        .then(b => createImageBitmap(b));

    const darkRequests  = Array.from({ length: NEBULA_LAYER_COUNT }, (_, l) => loadLayer('dark',  l));
    const lightRequests = Array.from({ length: NEBULA_LAYER_COUNT }, (_, l) => loadLayer('light', l));

    Promise.all([...darkRequests, ...lightRequests])
      .then(all => {
        if (cancelled) return;
        setBitmaps({
          dark:  all.slice(0, NEBULA_LAYER_COUNT),
          light: all.slice(NEBULA_LAYER_COUNT),
        });
      })
      .catch(err => {
        console.error('[useNebulaTexture] Failed to load nebula assets:', err);
      });

    return () => { cancelled = true; };
  }, [enabled]);

  return bitmaps;
}

